# Generated by Django 6.1.1 on 2026-09-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_resume_resume_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='cleaned_description',
            field=models.TextField(blank=True),
        ),
    ]
